#  Assignment 3

Title : Prepare Bag of words to perform Spam Filtering in the given Text passage provided.

Description : The students are required to analyse the text passage provided, tokenize and Lementise the text. Now apply technique to prepare Bag of Words and apply spam filtering methods to provide spam filtering solution.

Objective: Familiarity with NLP operations using NLTK and application in semantic analysis.

Domain : Natural Language Processing.

Steps to be taken:

1) Perform cleaning and tokenization.

2) Perform lementization after doing POS (parts of speech identifications) to avoid errors.

3) Prepare Bag of Words and perform Spam filtering from database of emails.

(The Dataset is attached in the Module NLP with the name as SPAM COLLECTION)

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, re
import nltk

In [2]:
df_spamCollection =pd.read_csv('E://Avantika Univeristy//Avantika University 4th year//Semester 7//Artificial intelligence advance//NLP//SpamCollection',sep='\t',names=['label','headers'])

In [3]:
df_spamCollection.head()

label                                            headers
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
import nlp_tools
import contractions

In [5]:
text = df_spamCollection['headers'][0]
text


'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [6]:
nlp_tools.lemmatization_sentence(text)

'go until jurong point crazy .. available only in bugis n great world la e buffet ... cine there get amore wat ...'

In [7]:
txt = "i don't like mail spams"
contractions.expand_contraction(txt)

'i do not like mail spams'

In [8]:
df_spamCollection['clean_headers'] = df_spamCollection['headers'].apply(contractions.expand_contraction)
df_spamCollection['clean_headers'] = df_spamCollection['clean_headers'].apply(nlp_tools.lemmatization_sentence)

In [9]:
df_spamCollection.head()

label                                            headers  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                       clean_headers  
0  go until jurong point crazy .. available only ...  
1                      ok lar ... joke wif u oni ...  
2  free entry in 2 a wkly comp to win fa cup fina...  
3  u dun say so early hor ... u c already then sa...  
4  nah i do not think he go to usf he live around...

In [10]:
df_spamCollection['clean_headers'].ndim

1

In [11]:
headers_list = df_spamCollection['clean_headers'].tolist()

In [12]:
type(headers_list)

list

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv= CountVectorizer()

In [15]:
cv.fit(headers_list) # all unique words in a array

CountVectorizer()

In [16]:
X = cv.transform(headers_list).toarray()

In [17]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
type(X)

numpy.ndarray

In [19]:
len(cv.get_feature_names())

7753

In [20]:
y = df_spamCollection['label'].values

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
model = MultinomialNB()

In [24]:
model.fit(x_train,y_train)

MultinomialNB()

In [25]:
y_pred = model.predict(x_test)

In [26]:
from sklearn import metrics

In [27]:
cr = metrics.classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1204
        spam       0.95      0.93      0.94       189

    accuracy                           0.98      1393
   macro avg       0.97      0.96      0.96      1393
weighted avg       0.98      0.98      0.98      1393



In [28]:
test_text ="Free entry in 2 a wkly comp to win T20 World Cup"

In [29]:
 #step-1: contraction
clean_text = contractions.expand_contraction(test_text)
#step-2: lemma
lema_text = nlp_tools.lemmatization_sentence(clean_text)
# step-3: bag of words
vector = cv.transform([lema_text]).toarray()
# step-4: machine learning model
res = model.predict(vector)
prob = model.predict_proba(vector)

In [30]:
res

array(['spam'], dtype='<U4')

In [31]:
prob

array([[1.48342153e-05, 9.99985166e-01]])

In [32]:
X[:3,:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
df_spam_1 = pd.DataFrame(X,columns=cv.get_feature_names())

In [34]:
df_spam_1

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  \
0              0   0  ...      0       0    0          0     0     0      0   
1              0   0  ...      0       0    0          0     0     0      0   
2              0   0  ...      0       0    0          0     0     0      0   
3              0   0  ...      0       0    0          0     0     0      0   
4              0   0  ...      0       0    0          0     0     0      0   
...          ...  ..  ...    ...     ...  ...        ...   ...   ...    ...   
5567           0   0  ...      0       0    0          0     0     0      0   
5568           0   0  ...      0       0    0          0     0     0      0   
5569           0   0  ...      0       0    0          0     0     0      0   
5570           0   0  ...      0       0    0          0     0     0      0   
5571           0   0  ...      0       0    0          0     0     0      0   

      èn  ú1  〨ud  
0      0   0    0  
1      0   0    0  
2      0   0    0  
3      0   0    0  
4      0   0    0  
...   ..  ..  ...  
5567   0   0    0  
5568   0   0    0  
5569   0   0    0  
5570   0   0    0  
5571   0   0    0  

[5572 rows x 7753 columns]

Submitted by-
- Jayant Choudhary
- AU18B1003